option(BUILD_3RDPARTY "Build 3rdparty" ON)
if (BUILD_3RDPARTY)
    set(BUILD_3RDPARTY_THREADS 8)
    set(THIRD_PARTY_BUILD_VER_FILE ${PROJECT_SOURCE_DIR}/3rdparty/BUILD_VER.txt)
    set(THIRD_PARTY_BUILT_VER 2)
    set(BUILD_THIRD_PARTY TRUE)
    if (EXISTS ${THIRD_PARTY_BUILD_VER_FILE})
        file(READ ${THIRD_PARTY_BUILD_VER_FILE} READ_THIRD_PARTY_BUILT_VER)
        if (NOT READ_THIRD_PARTY_BUILT_VER LESS THIRD_PARTY_BUILT_VER)
            set(BUILD_THIRD_PARTY FALSE)
        endif (NOT READ_THIRD_PARTY_BUILT_VER LESS THIRD_PARTY_BUILT_VER)
    endif (EXISTS ${THIRD_PARTY_BUILD_VER_FILE})

    if (BUILD_THIRD_PARTY)
        message(STATUS "Your Third Party Dependencies are old version. You can build up-to-date version with target 'BuildThirdPartyLib'.")
        include(Install3rdParty)
        return()
    endif (BUILD_THIRD_PARTY)
endif (BUILD_3RDPARTY)